(() => {
  const bible = window.WorldBible;
  const content = document.querySelector('#page-content');
  const page = document.body.dataset.page;
  const nav = document.querySelector('#site-nav');
  const navItems = [['index.html','Home'],['atlas.html','Atlas'],['catalogue.html','Catalogue'],['industries.html','Industries'],['rules.html','World Rules']];
  nav.innerHTML = navItems.map(([href,label]) => `<a class="${location.pathname.endsWith(href) || (href === 'index.html' && location.pathname.endsWith('/world-bible/')) ? 'active' : ''}" href="${href}">${label}</a>`).join('');
  const badge = (status) => `<span class="badge ${status.toLowerCase().replaceAll(' ','-')}">${status}</span>`;
  const linkEntry = (entry) => `<a class="catalogue-card" href="entry.html#${entry.id}"><span class="card-icon">${entry.icon}</span><span class="card-body">${badge(entry.status)}<strong>${entry.name}</strong><small>${entry.type} · ${entry.habitat}</small></span><span class="arrow">↗</span></a>`;
  const section = (eyebrow, title, copy, body) => `<section class="section"><p class="eyebrow">${eyebrow}</p><h2>${title}</h2>${copy ? `<p class="section-copy">${copy}</p>` : ''}${body}</section>`;

  function home() {
    content.innerHTML = `<section class="hero"><div class="hero-copy"><p class="eyebrow">Creator reference · canonical world knowledge</p><h1>THE WORLD<br><em>BEFORE</em> THE CHRONICLE</h1><p>The Overseer World Bible records what exists, what may exist, and what remains only a blueprint. It is a living reference for a persistent world—not a player-facing map.</p><div class="hero-actions"><a class="button gold" href="atlas.html">Enter the Atlas</a><a class="button ghost" href="catalogue.html">Browse Catalogue</a></div></div><aside class="seed-card"><span>Canonical seed</span><strong>${bible.seed}</strong><dl><div><dt>Atlas extent</dt><dd>280 × 200 km</dd></div><div><dt>Strategic cell</dt><dd>10 km region</dd></div><div><dt>Human civilization</dt><dd>None</dd></div><div><dt>World memory</dt><dd>Persistent</dd></div></dl></aside></section>${section('World state', 'A world with consequences', 'The page is deliberately honest about implementation readiness.', `<div class="state-grid"><article><b>${bible.biomes.length}</b><span>seed-supported macro-biomes</span></article><article><b>${bible.entries.filter(e=>e.status==='Seed-supported').length}</b><span>reference entries grounded now</span></article><article><b>${bible.topology.length}</b><span>topology families awaiting implementation</span></article><article><b>0</b><span>active human civilizations</span></article></div>`)}${section('Reference paths', 'Read the world by its own categories', '', `<div class="path-grid"><a href="atlas.html"><span>🗺️</span><strong>Atlas & ecology</strong><small>Biomes, topology, sites and seed constraints.</small></a><a href="catalogue.html"><span>🦫</span><strong>Living catalogue</strong><small>Flora, wildlife, monsters, native peoples and materials.</small></a><a href="industries.html"><span>⚒️</span><strong>Human impact</strong><small>Handwork, agriculture, textiles, forestry and industry.</small></a><a href="rules.html"><span>◈</span><strong>World laws</strong><small>Identity, history, consequence and persistence.</small></a></div>`)}`;
  }
  function atlas() {
    const biomeCards = bible.biomes.map(b => `<article class="biome-card"><span>${b.icon}</span><div>${badge(b.status)}<h3>${b.name}</h3><code>${b.key}</code><p>${b.detail}</p></div></article>`).join('');
    const topo = bible.topology.map(t => `<article class="topology-card"><span>${t.icon}</span><div>${badge(t.status)}<h3>${t.name}</h3><p>${t.detail}</p></div></article>`).join('');
    content.innerHTML = `<section class="page-hero compact"><p class="eyebrow">The original geography</p><h1>OVERSEER ATLAS</h1><p>The seed is a persistent geography. Atlas markers are creator knowledge and never reveal a player’s map.</p></section><section class="atlas-frame"><div class="atlas-image"><img src="assets/overseer-atlas-v1.png" alt="Illustrated Project Draugr creator atlas" /><div class="atlas-markers"><i class="resource" title="Resource sites"></i><i class="wildlife" title="Wildlife ranges"></i><i class="monster" title="Monster territories"></i><i class="ruin" title="Ancient ruins"></i></div></div><aside><p class="eyebrow">Reading the map</p><h2>Geography first</h2><p>Resources, wildlife ranges, lairs and ruins must be physically placed. A marker improves abundance or records a concentration; it never creates the only source of basic survival.</p><dl><div><dt>Resource</dt><dd>Concentrated material / water / forage</dd></div><div><dt>Wildlife</dt><dd>Range, den, nesting or migration ground</dd></div><div><dt>Monster</dt><dd>Lair, territory or rare ecological niche</dd></div><div><dt>Ruin</dt><dd>Persistent ancient structure and evidence</dd></div></dl></aside></section>${section('Macro-biomes','The land that already exists','Six macro-biomes form the current canonical seed.', `<div class="biome-grid">${biomeCards}</div>`)}${section('Required topology','The places that make a label true','These are planned world layers. Dependent content remains inactive until they exist.', `<div class="topology-grid">${topo}</div>`)}`;
  }
  function catalogue() {
    const types = ['All', ...new Set(bible.entries.map(e=>e.type))];
    content.innerHTML = `<section class="page-hero compact"><p class="eyebrow">No reward tables · only physical consequence</p><h1>LIVING CATALOGUE</h1><p>Every card states whether it is supported by the current seed, requires topology, or remains a blueprint.</p></section><section class="catalogue-toolbar"><label>Search <input id="search" placeholder="Rabbit, flint, wetland…" /></label><div id="filters">${types.map(t=>`<button class="${t==='All'?'selected':''}" data-filter="${t}">${t}</button>`).join('')}</div></section><section class="catalogue-grid" id="catalogue-grid"></section>`;
    let active = 'All'; const grid = document.querySelector('#catalogue-grid'); const search = document.querySelector('#search');
    const render = () => { const term = search.value.toLowerCase(); grid.innerHTML = bible.entries.filter(e => (active==='All'||e.type===active) && `${e.name} ${e.type} ${e.habitat} ${e.status}`.toLowerCase().includes(term)).map(linkEntry).join('') || `<p class="empty">No world-bible entry matches that search.</p>`; };
    document.querySelector('#filters').addEventListener('click', e=>{ if(e.target.tagName!=='BUTTON')return; active=e.target.dataset.filter; document.querySelectorAll('#filters button').forEach(b=>b.classList.toggle('selected',b===e.target));render();}); search.addEventListener('input',render); render();
  }
  function industries() {
    content.innerHTML = `<section class="page-hero compact"><p class="eyebrow">Civilization changes the land</p><h1>PHYSICAL SECTORS</h1><p>Every sector uses local material, labour and time; produces outputs and waste; affects habitats; and creates maintenance and recovery work.</p></section><section class="industry-list">${bible.industries.map(i=>`<article><span class="industry-icon">${i.icon}</span><div>${badge(i.status)}<h2>${i.name}</h2><p class="chain">${i.chain}</p><p>${i.rule}</p><small>Specification tickets: ${i.issues}</small></div></article>`).join('')}</section>${section('Consequence contract','No industry is isolated','Work affects actor physiology, land, water, air, wildlife, monsters, native peoples, property, routes and future maintenance.', `<div class="impact-line"><span>Effort</span><b>→</b><span>Footprint</span><b>→</b><span>Response</span><b>→</b><span>Recovery</span></div>`)}`;
  }
  function rules() {
    content.innerHTML = `<section class="page-hero compact"><p class="eyebrow">The Overseer’s contract</p><h1>WORLD LAWS</h1><p>These are not flavour text. They are the rules every future catalogue entry, industry and simulation feature must satisfy.</p></section><section class="rule-list">${bible.rules.map(([title,copy],index)=>`<article><span>${String(index+1).padStart(2,'0')}</span><div><h2>${title}</h2><p>${copy}</p></div></article>`).join('')}</section>${section('Activity impact','What every meaningful procedure must leave behind','A procedure is only complete when it has actor cost, physical inputs, footprint, output/waste, affected beings, time/neglect consequences and recovery paths.', `<div class="impact-line"><span>Actor</span><b>→</b><span>Inputs</span><b>→</b><span>Footprint</span><b>→</b><span>World response</span><b>→</b><span>History</span></div>`)}`;
  }
  function entry() {
    const id = location.hash.slice(1); const e = bible.entries.find(x=>x.id===id) || bible.entries[0]; document.title = `${e.name} — Project Draugr World Bible`;
    content.innerHTML = `<a class="back-link" href="catalogue.html">← Back to catalogue</a><section class="entry-hero"><div class="entry-icon">${e.icon}</div><div><p class="eyebrow">${e.type} · ${e.latin}</p>${badge(e.status)}<h1>${e.name}</h1><p>${e.habitat}</p></div></section><section class="entry-layout"><article class="entry-main"><div><h2>Behaviour & presence</h2><p>${e.behaviour}</p></div><div><h2>Ecological role</h2><p>${e.role}</p></div><div><h2>Physical recovery / harvest</h2><p>${e.recovery}</p></div><div><h2>Risk & consequence</h2><p>${e.danger}</p></div></article><aside class="entry-meta"><p class="eyebrow">Classification</p><dl><div><dt>Type</dt><dd>${e.type}</dd></div><div><dt>Status</dt><dd>${e.status}</dd></div><div><dt>Habitat</dt><dd>${e.habitat}</dd></div><div><dt>Related work</dt><dd>${e.related}</dd></div></dl><p class="muted">Catalogue entries describe physical possibilities. They do not grant the Chronicle knowledge, ownership, access or safety.</p></aside></section>`;
  }
  ({home,atlas,catalogue,industries,rules,entry}[page] || home)();
})();
