/* Static creator-reference data. Status is intentionally visible: planned content
   is never presented as active simulation content. */
window.WorldBible = {
  seed: '681013497',
  biomes: [
    { icon: '🌲', name: 'Temperate Forest', key: 'TEMPERATE_FOREST', status: 'Seed-supported', detail: 'Canopy, old growth, deadfall, understory and leaf litter. The richest first-hours source for shelter stock, fibre, forage, small wildlife and wood.' },
    { icon: '🌾', name: 'Grassland', key: 'GRASSLAND', status: 'Seed-supported', detail: 'Open wind-exposed ground with grasses, seed heads, grazing routes, field stone and long sightlines. Strong for early food, fibre and herd ecology.' },
    { icon: '🪷', name: 'Wetland', key: 'WETLAND', status: 'Seed-supported', detail: 'Waterlogged ground, reeds, clay, amphibious life and standing water. Productive but hazardous: rot, depth, contamination and disease matter.' },
    { icon: '⛰️', name: 'Highland', key: 'HIGHLAND', status: 'Seed-supported', detail: 'Open slopes, thin turf, exposed stone and wind. Supports stone, hardy plants, goat/reindeer routes and difficult travel.' },
    { icon: '🏔️', name: 'Mountain', key: 'MOUNTAIN', status: 'Seed-supported', detail: 'Cold, rocky, sparse and dangerous. A source of exposed geology, but never a guarantee of shelter, food, or safe access.' },
    { icon: '🌊', name: 'Ocean', key: 'OCEAN', status: 'Seed-supported', detail: 'Open salt water and weather exposure. A coast is not implied: shore, estuary and tidal ecology require explicit topology.' }
  ],
  topology: [
    { icon: '〰️', name: 'Freshwater hydrology', status: 'Topology required', detail: 'Headwaters, streams, rivers, lake margins, floodplains, fords and marsh islands. Enables river-dependent life, irrigation and real migration corridors.' },
    { icon: '🪨', name: 'Cave & karst', status: 'Topology required', detail: 'Cave mouths, interiors, drainage, ventilation, darkness and quarry interfaces. Required before cave peoples, cave shelters or subterranean ecology activate.' },
    { icon: '🏝️', name: 'Littoral coast', status: 'Topology required', detail: 'Beach, rocky shore, tidal flat, estuary, dune, shell bed and coastal cliff. Prevents ocean content from appearing in featureless open water.' },
    { icon: '🌋', name: 'Rare geology', status: 'Topology required', detail: 'Finite deposits for copper, tin, iron, gold, silver/lead, refractory clay, limestone, iron sand, and—where coherent—obsidian and sulphur.' }
  ],
  entries: [
    { id:'rabbit', icon:'🐇', type:'Wildlife', status:'Seed-supported', name:'Rabbit', latin:'Small grassland / forest-edge herbivore', habitat:'Grassland and temperate forest; warren or cover is required.', behaviour:'Crepuscular, alert, flee-first. Feeding sign, tracks, droppings and disturbed grass are more likely to be found than the animal.', role:'Prey and seed disperser; its population is limited by food, cover, predation, season and hunting pressure.', recovery:'After a lawful physical kill: a persistent carcass may yield meat, hide, bones and limited sinew through a valid field-dressing chain. A missed hunt leaves the population unchanged.', danger:'Low direct danger; starvation, poor traps, disease and overhunting are the real risks.', related:'#74 · #87–#93 · #207–#214' },
    { id:'red-squirrel', icon:'🐿️', type:'Wildlife', status:'Seed-supported', name:'Red Squirrel', latin:'Canopy herbivore and cache-maker', habitat:'Temperate forest with cone- and mast-bearing trees.', behaviour:'Diurnal, quick to flee, caches food and can alter seed dispersal over seasons.', role:'Forest seed movement and prey biomass.', recovery:'A carcass is small and yields little; shed fur, gnawed cones and feeding signs are more common evidence.', danger:'Low. Disturbance and canopy loss drive local avoidance or range shift.', related:'#74 · #84 · #200–#206 · #207–#214' },
    { id:'beaver', icon:'🦫', type:'Wildlife', status:'Seed-supported', name:'Beaver', latin:'Amphibious ecosystem engineer', habitat:'Wetland or future river/lake topology with woody banks and stable water.', behaviour:'Crepuscular, territorial around lodge and food stores; avoids repeated danger but can defend close range.', role:'Changes local water, habitat and sediment. A lodge is not decoration.', recovery:'Physical carcass recovery only after a valid outcome; lodge timber, dams and food caches are property-like ecological works, not free loot.', danger:'Medium around water and close territory. Dam removal may trigger local hydrology consequences.', related:'#74 · #156 · #207–#214' },
    { id:'hare', icon:'🐇', type:'Wildlife', status:'Seed-supported', name:'Hare', latin:'Open-ground seasonal herbivore', habitat:'Grassland and forest margins with cover and forage.', behaviour:'Nocturnal or crepuscular; relies on stillness and rapid escape rather than confrontation.', role:'Prey base for foxes, wolves and raptors.', recovery:'Persistent carcass, if killed, supports limited meat/hide/bone recovery through a real procedure.', danger:'Low direct danger; high sensitivity to traps, weather and predator pressure.', related:'#74 · #88–#93 · #132' },
    { id:'wild-boar', icon:'🐗', type:'Wildlife', status:'Seed-supported', name:'Wild Boar', latin:'Territorial forest omnivore', habitat:'Temperate forest, wet margins and grassland edges.', behaviour:'Rooting, feeding groups, defensive when cornered or with young. Not a passive food source.', role:'Soil disturbance, forage competition, predator prey and future husbandry candidate.', recovery:'Carcass can yield meat, hide, bone, fat and sinew only after a credible hunt or recovery; local population changes once per death.', danger:'High at close range; tusk wounds and defensive charges are plausible.', related:'#74 · #79 · #87–#93 · #207–#214' },
    { id:'river-trout', icon:'🐟', type:'Wildlife', status:'Topology required', name:'River Trout', latin:'Cold freshwater predator', habitat:'Future fast stream / river topology with oxygenated water and connected spawning routes.', behaviour:'Avoids noise and shadow; seasonal movement follows water quality and temperature.', role:'Freshwater food web indicator.', recovery:'Fishing must leave a physical catch and affect a real local population; no fish are available where no water body exists.', danger:'Low to Chronicle; sensitive to sediment, pollution and water diversion.', related:'#74 · #156 · #207–#214' },
    { id:'dire-wolf', icon:'🐺', type:'Monster', status:'Seed-supported', name:'Dire Wolf', latin:'Large coordinated territorial predator', habitat:'Temperate forest and highland pack ground.', behaviour:'Crepuscular, pack-oriented, risk-aware. It hunts, rests, avoids injury and remembers repeated threat.', role:'Apex pressure on herd and prey populations.', recovery:'A dead individual becomes a persistent carcass. Removing an alpha or repeated pack members can alter territory, breeding and local prey balance.', danger:'High. Pack response, wounded prey, territory and Chronicle condition matter more than a level number.', related:'#86 · #121–#122 · #207–#214' },
    { id:'bog-wraith', icon:'🫧', type:'Monster', status:'Seed-supported', name:'Bog Wraith', latin:'Wetland territorial organism', habitat:'Wetland lair territory; not a generic night encounter.', behaviour:'Nocturnal and aggressive near its territory. Its danger comes from wound disease and the environment as much as direct contact.', role:'Rare wetland predator / hazard.', recovery:'Any remains or specialised material must be a physically justified outcome; it is never a reward table.', danger:'High. Wet ground, disease, darkness and poor escape routes amplify risk.', related:'#86 · #84 · #207–#214' },
    { id:'wyvern', icon:'🪽', type:'Monster', status:'Seed-supported', name:'Wyvern', latin:'Rare mountain aerial apex predator', habitat:'Remote mountain territory with viable prey and roost access.', behaviour:'Nocturnal, territorial and injury-averse. It may observe, avoid, defend a nest or hunt depending on local state.', role:'Apex aerial predator with ecosystem-scale impact.', recovery:'A death is extraordinary: body, nest, possessions and territory remain physical consequences with ecological and social ramifications.', danger:'Extreme. A newly awakened Chronicle should avoid, not defeat, this creature.', related:'#86 · #117 · #132 · #207–#214' },
    { id:'goblin-band', icon:'🪵', type:'Native people', status:'Blueprint', name:'Goblin Band', latin:'Tier IIb cunning folk', habitat:'Future cave/root-burrow, scrub ravine, quarry margin or ruin-edge topology.', behaviour:'Social, tool-using, territorial and capable of trade, defence, theft, retreat, negotiation and retaliation.', role:'Potential native community, never disposable wildlife.', recovery:'Homes, stores, graves, property and bodies carry personhood and social consequences. Killing can close trade or trigger durable retaliation.', danger:'Variable. Their response follows community state, leadership, territory and prior relationship.', related:'#119 · #120 · #158 · #207–#214' },
    { id:'centaur-herd', icon:'🏇', type:'Native people', status:'Blueprint', name:'Centaur Herd', latin:'Tier III grassland / forest-edge people', habitat:'Grassland, woodland meadow and route ecology with open movement and grazing capacity.', behaviour:'Herd/community social structure; movement, property, agreements, trade and territory are physical and persistent.', role:'Potential grassland native culture, not a mounted-combat shortcut.', recovery:'No loot abstraction. A death creates an individual, community and burial/property consequence.', danger:'Variable and relational; cooperation is possible only through earned conduct.', related:'#118 · #121–#122 · #159 · #207–#214' },
    { id:'reedkin', icon:'🪷', type:'Native people', status:'Topology required', name:'Reedkin', latin:'Tier III amphibious river people', habitat:'Large wetland, delta, lake margin or river-island topology with dry shelter and water quality.', behaviour:'Community-oriented, site-bound, affected directly by sediment, water withdrawal, reeds loss and pollution.', role:'Potential wetland native culture and waterway stakeholder.', recovery:'Personhood, homes, boats, stores, graves and agreements are persistent. No universal water breathing or travel shortcut.', danger:'Variable. Industrial water damage may cause negotiation, obstruction, migration or retaliation.', related:'#118 · #156 · #207–#214' },
    { id:'oak', icon:'🌳', type:'Flora', status:'Seed-supported', name:'Oak', latin:'Mature temperate hardwood', habitat:'Temperate forest and highland woodland.', behaviour:'Long-lived living stand member; mast and canopy affect wildlife, soil, shade and habitat.', role:'Timber, bark, acorn, mast habitat and old-growth ecology.', recovery:'Deadfall and lawful harvest have different routes. Live felling needs a suitable tool and changes the woodland state; bark removal can injure a living tree.', danger:'Low direct danger; high ecological consequence if overcut.', related:'#85 · #200–#206 · #180' },
    { id:'nettle', icon:'🌿', type:'Flora', status:'Seed-supported', name:'Stinging Nettle', latin:'Fibre and food herb', habitat:'Forest edge, grassland and wetland margins.', behaviour:'Seasonal herb; regrowth and patch depletion matter.', role:'Fibre, leaf food after preparation and habitat for insects.', recovery:'Leaves and stems are separate physical yields. Bare-hand harvest can sting; processing fibre needs its own chain.', danger:'Minor skin irritation; food safety depends on preparation.', related:'#85 · #137 · #171–#179 · #191–#199' },
    { id:'cattail', icon:'🌾', type:'Flora', status:'Seed-supported', name:'Cattail', latin:'Wetland reed and starch plant', habitat:'Wetland and future riverbank/lake margin sites.', behaviour:'Water-rooted; harvest pressure and water condition matter.', role:'Stalk, fluff, leaf, fibre and edible root routes.', recovery:'Different plant parts require different access and preparation. Digging roots is not the same action as gathering fluff.', danger:'Wet ground, water depth and contamination constrain harvest.', related:'#85 · #156 · #162 · #171 · #191' },
    { id:'blackberry', icon:'🫐', type:'Flora', status:'Seed-supported', name:'Blackberry', latin:'Thorny fruiting shrub', habitat:'Forest edge and grassland/scrub margins.', behaviour:'Seasonal fruit and thorny cane; supports wildlife as well as Chronicle food.', role:'Food, barriers, cane and animal forage.', recovery:'Fruit harvest is finite and seasonal; canes have a separate physical use route.', danger:'Thorns, overharvest and spoiled fruit.', related:'#85 · #60 · #162 · #200' },
    { id:'porcini', icon:'🍄', type:'Flora', status:'Seed-supported', name:'Porcini', latin:'Forest mycorrhizal fungus', habitat:'Temperate forest and highland woodland.', behaviour:'Seasonal, moisture-dependent and tied to living woodland ecology.', role:'Food and forest decomposition relationships.', recovery:'A gathered mushroom is perishable; it cannot be safely confused with every other fungus.', danger:'Misidentification remains a real consequence.', related:'#85 · #60 · #200 · #215' },
    { id:'flint', icon:'🪨', type:'Material', status:'Seed-supported', name:'Flint / chert source', latin:'Knappable stone', habitat:'Highland, grassland or mountain geological exposure.', behaviour:'Finite, geology-bound and quality-variable.', role:'Edges, points, fire-starting interfaces and toolmaking.', recovery:'Gathered nodule/cobble needs testing, core reduction and knapping. A random field stone is not automatically flint.', danger:'Sharp flakes and hand injury; waste chips remain physical debris.', related:'#75 · #78 · #136 · #180' },
    { id:'clay', icon:'🏺', type:'Material', status:'Seed-supported', name:'Surface Clay', latin:'Plastic earth material', habitat:'Wetland, riverbank or dedicated clay deposit overlay.', behaviour:'Wet, heavy and water-sensitive until properly processed.', role:'Temporary shaping, ceramics, daub, kiln/furnace refractories.', recovery:'Surface clay, refined clay and fired ceramic are separate states. Unfired shapes are fragile and water-sensitive.', danger:'Excavation, sediment and water impacts matter.', related:'#59 · #77–#78 · #156 · #160 · #180' },
    { id:'copper', icon:'🟠', type:'Material', status:'Topology required', name:'Copper Ore', latin:'Finite metal-bearing geological stock', habitat:'Approved malachite/azurite vein or exposure only.', behaviour:'Grade, access, waste rock and extraction hazard vary by deposit.', role:'Future copper and bronze chains.', recovery:'Ore requires crushing, roasting, fuel, airflow, refractory facility and slag management. It never becomes a tool directly.', danger:'Mining collapse, smoke, heat, tailings and habitat disruption.', related:'#160 · #181–#185 · #207–#221' },
    { id:'iron', icon:'⚙️', type:'Material', status:'Topology required', name:'Iron Ore', latin:'Hematite, magnetite or bog iron', habitat:'Approved finite vein, bog-iron patch or iron-sand bar.', behaviour:'Deposit-specific grade and depletion; cannot be inferred from any mountain tile.', role:'Future bloomery and wrought-iron chains.', recovery:'Requires a complete fuel, refractory, airflow and bloom-consolidation chain. Failure leaves bloom slag and physical evidence.', danger:'Extraction, heat, smoke, heavy loads and water/soil impacts.', related:'#160 · #181 · #186–#190 · #215' },
    { id:'gold', icon:'🟡', type:'Material', status:'Topology required', name:'Placer Gold', latin:'Rare heavy metal', habitat:'Approved river-gravel bar or native pocket only.', behaviour:'Scarce, finite and physically heavy.', role:'Later craft, record, ceremonial or exchange material only when society creates a real use.', recovery:'Panning and recovery require water, sediment handling and a valid deposit. It is never an abstract currency drop.', danger:'Environmental disruption, theft/property conflict and social consequence.', related:'#156 · #160 · #181 · #188 · #211' }
  ],
  industries: [
    { icon:'✋', name:'Bare-hand handwork', status:'M1 foundation', chain:'Gather → assess → twist, bind, fold, shape → fragile use → salvage', rule:'No cutting, drilling, knapping, controlled high heat or hidden free craft. Low-capacity results fail when wet, overloaded or abraded.', issues:'#191–#199' },
    { icon:'🌱', name:'Agriculture', status:'M2 sector', chain:'Wild source → viable seed → plot → sow → seasonal crop → harvest → storage → replant', rule:'A crop is a rooted physical population. Drought, frost, pests, browsing, labour interruption and bad storage can destroy it.', issues:'#162–#170' },
    { icon:'🧶', name:'Textiles', status:'M2 sector', chain:'Fibre → clean / ret → spin → yarn → weave / felt → garment → repair / reuse', rule:'Fibre source, water, labour, tool, fit, wetness, wear and repair are all real. Wool/hide sources require welfare or lawful remains.', issues:'#171–#179' },
    { icon:'🌲', name:'Forestry', status:'M2 sector', chain:'Living stand → survey → recover / harvest → season → transport → use → regrowth', rule:'Forests are not infinite wood pools. Deadfall, live stands, coppice, canopy and habitat have different states and consequences.', issues:'#200–#206' },
    { icon:'⚒️', name:'Heavy industry', status:'M2 sector', chain:'Finite deposit → extraction → fuel / refractory → kiln / furnace → stock → object → waste / recycle', rule:'No ore-to-tool shortcut. Heat, airflow, fuel, water, waste, hauling, safety and site depletion are mandatory.', issues:'#180–#190' }
  ],
  rules: [
    ['Identity never changes', 'Every physical object has a UUID. Objects are not deleted merely because they are lost, used up, destroyed, or no longer owned.'],
    ['Current state is authoritative', 'The world’s present locations, conditions, containment, ownership and ecology are the truth used by play.'],
    ['History is immutable', 'Actions and consequences leave an enduring record. Repairs and recovery do not erase past damage.'],
    ['Everything has a place', 'Every object always has a physical location or owner. Remote access is not allowed.'],
    ['Ecology is alive', 'Wildlife, monsters and native peoples respond to real food, territory, disturbance, routes, property and relationships. They do not silently despawn.'],
    ['No catalogue-only content', 'An entry may only become active when it has seed-compatible habitat, physical sources, a procedure, lifecycle, tests and Auditor evidence.'],
    ['The narrator witnesses', 'Narration describes physical results. It does not disclose hidden recipes, rescue a careless Chronicle, or act as a hint system.'],
    ['The world remembers', 'Every life leaves a mark. The world remembers. The Overseer never forgets.']
  ]
};
