-- V225 — story #86: 30 scarce, habitat-bound monster species. Each is a MONSTRUM registry species (so confront and
-- the ecology systems know what it is) AND a monster_profile (movement, resistance, aggression, activity, sight,
-- special mechanic, biome). They are NOT ordinary ambient fauna — the #86 presentLife change excludes MONSTRUM from
-- the casual cast and instead lets a keen eye catch a rare, uncanny SIGN of one, so the world feels inhabited by
-- uncanny things without every region becoming a combat arena. Pure data on the existing ecology tables.
INSERT INTO wildlife_species (species_key, kingdom_class, ecological_role, activity_cycle, movement_class, size_tier, base_resistance, ambush_hunter, pack_hunter, territorial, tamability, biome_affinity) VALUES
('mossback_elk',          'MONSTRUM','HERBIVORE','CREPUSCULAR','TERRESTRIAL','HUGE',  80, FALSE, FALSE, TRUE, 0, 'TEMPERATE_FOREST'),
('thornhide_boar',        'MONSTRUM','OMNIVORE', 'DIURNAL',    'TERRESTRIAL','LARGE', 70, FALSE, FALSE, TRUE, 0, 'TEMPERATE_FOREST'),
('hollow_stag',           'MONSTRUM','HERBIVORE','NOCTURNAL',  'TERRESTRIAL','LARGE', 60, FALSE, FALSE, TRUE, 0, 'TEMPERATE_FOREST'),
('root_burrower',         'MONSTRUM','OMNIVORE', 'NOCTURNAL',  'TERRESTRIAL','MEDIUM',55, FALSE, FALSE, TRUE, 0, 'TEMPERATE_FOREST'),
('shade_panter',          'MONSTRUM','CARNIVORE','NOCTURNAL',  'TERRESTRIAL','MEDIUM',65, TRUE,  FALSE, TRUE, 0, 'TEMPERATE_FOREST'),
('widow_spider_colony',   'MONSTRUM','CARNIVORE','NOCTURNAL',  'TERRESTRIAL','SMALL', 30, TRUE,  TRUE,  TRUE, 0, 'TEMPERATE_FOREST'),
('reed_stalker',          'MONSTRUM','CARNIVORE','NOCTURNAL',  'AMPHIBIOUS', 'MEDIUM',60, TRUE,  FALSE, TRUE, 0, 'WETLAND'),
('mud_tortoise_colossus', 'MONSTRUM','HERBIVORE','DIURNAL',    'AMPHIBIOUS', 'HUGE', 100, FALSE, FALSE, TRUE, 0, 'WETLAND'),
('drowned_eel',           'MONSTRUM','CARNIVORE','NOCTURNAL',  'AQUATIC',    'MEDIUM',50, TRUE,  FALSE, TRUE, 0, 'WETLAND'),
('mire_leech_cluster',    'MONSTRUM','CARNIVORE','NOCTURNAL',  'AQUATIC',    'SMALL', 20, FALSE, TRUE,  FALSE,0, 'WETLAND'),
('glassfin_pike',         'MONSTRUM','CARNIVORE','DIURNAL',    'AQUATIC',    'MEDIUM',40, FALSE, FALSE, TRUE, 0, 'WETLAND'),
('willow_wisp_swarm',     'MONSTRUM','OMNIVORE', 'NOCTURNAL',  'AERIAL',     'TINY',  15, FALSE, TRUE,  FALSE,0, 'WETLAND'),
('ashhorn_antelope',      'MONSTRUM','HERBIVORE','DIURNAL',    'TERRESTRIAL','MEDIUM',35, FALSE, FALSE, FALSE,0, 'GRASSLAND'),
('burrow_ogre',           'MONSTRUM','OMNIVORE', 'NOCTURNAL',  'TERRESTRIAL','LARGE', 75, FALSE, FALSE, TRUE, 0, 'GRASSLAND'),
('dust_mantis',           'MONSTRUM','CARNIVORE','DIURNAL',    'TERRESTRIAL','MEDIUM',45, TRUE,  FALSE, TRUE, 0, 'GRASSLAND'),
('cinder_jackal_pack',    'MONSTRUM','SCAVENGER','CREPUSCULAR','TERRESTRIAL','MEDIUM',50, FALSE, TRUE,  TRUE, 0, 'GRASSLAND'),
('thunder_lizard',        'MONSTRUM','HERBIVORE','DIURNAL',    'TERRESTRIAL','HUGE',  95, FALSE, FALSE, TRUE, 0, 'GRASSLAND'),
('glass_scavenger_beetle','MONSTRUM','SCAVENGER','DIURNAL',    'TERRESTRIAL','SMALL', 25, FALSE, FALSE, FALSE,0, 'GRASSLAND'),
('crag_hyena',            'MONSTRUM','SCAVENGER','NOCTURNAL',  'TERRESTRIAL','MEDIUM',55, FALSE, TRUE,  TRUE, 0, 'MOUNTAIN,HIGHLAND'),
('stonehorn_ram',         'MONSTRUM','HERBIVORE','DIURNAL',    'TERRESTRIAL','LARGE', 60, FALSE, FALSE, TRUE, 0, 'MOUNTAIN,HIGHLAND'),
('cave_screecher',        'MONSTRUM','CARNIVORE','NOCTURNAL',  'AERIAL',     'SMALL', 40, TRUE,  FALSE, TRUE, 0, 'MOUNTAIN'),
('ironmaw_mole',          'MONSTRUM','OMNIVORE', 'NOCTURNAL',  'TERRESTRIAL','MEDIUM',50, FALSE, FALSE, TRUE, 0, 'MOUNTAIN,HIGHLAND'),
('frostwing_owl',         'MONSTRUM','CARNIVORE','NOCTURNAL',  'AERIAL',     'SMALL', 35, TRUE,  FALSE, TRUE, 0, 'HIGHLAND,MOUNTAIN'),
('ember_newt',            'MONSTRUM','CARNIVORE','NOCTURNAL',  'AMPHIBIOUS', 'TINY',  20, FALSE, FALSE, TRUE, 0, 'WETLAND'),
('saltback_crocodilian',  'MONSTRUM','CARNIVORE','NOCTURNAL',  'AMPHIBIOUS', 'LARGE',100, TRUE,  FALSE, TRUE, 0, 'COAST,WETLAND'),
('wave_roc',              'MONSTRUM','CARNIVORE','DIURNAL',    'AERIAL',     'HUGE',  90, FALSE, FALSE, TRUE, 0, 'COAST,MOUNTAIN'),
('storm_moth_cloud',      'MONSTRUM','HERBIVORE','NOCTURNAL',  'AERIAL',     'TINY',  15, FALSE, TRUE,  FALSE,0, 'GRASSLAND,COAST'),
('bonecrab',              'MONSTRUM','SCAVENGER','NOCTURNAL',  'AMPHIBIOUS', 'SMALL', 35, FALSE, FALSE, TRUE, 0, 'COAST'),
('pale_wolf',             'MONSTRUM','CARNIVORE','NOCTURNAL',  'TERRESTRIAL','MEDIUM',60, FALSE, TRUE,  TRUE, 0, 'HIGHLAND,MOUNTAIN'),
('worldroot_serpent',     'MONSTRUM','CARNIVORE','NOCTURNAL',  'TERRESTRIAL','HUGE', 110, TRUE,  FALSE, TRUE, 0, 'TEMPERATE_FOREST,MOUNTAIN')
ON CONFLICT (species_key) DO NOTHING;

INSERT INTO monster_profile (species_key, movement_class, resistance, aggression, activity_cycle, sight_radius, special_mechanic, biome_affinity) VALUES
('mossback_elk',          'TERRESTRIAL', 80,'DEFENSIVE', 'CREPUSCULAR',1,NULL,        'TEMPERATE_FOREST'),
('thornhide_boar',        'TERRESTRIAL', 70,'DEFENSIVE', 'DIURNAL',    1,NULL,        'TEMPERATE_FOREST'),
('hollow_stag',           'TERRESTRIAL', 60,'PASSIVE',   'NOCTURNAL',  1,NULL,        'TEMPERATE_FOREST'),
('root_burrower',         'TERRESTRIAL', 55,'DEFENSIVE', 'NOCTURNAL',  1,'GROUND_COLLAPSE','TEMPERATE_FOREST'),
('shade_panter',          'TERRESTRIAL', 65,'AGGRESSIVE','NOCTURNAL',  2,NULL,        'TEMPERATE_FOREST'),
('widow_spider_colony',   'TERRESTRIAL', 30,'DEFENSIVE', 'NOCTURNAL',  1,'VENOM',     'TEMPERATE_FOREST'),
('reed_stalker',          'AMPHIBIOUS',  60,'AGGRESSIVE','NOCTURNAL',  1,NULL,        'WETLAND'),
('mud_tortoise_colossus', 'AMPHIBIOUS', 100,'DEFENSIVE', 'DIURNAL',    1,NULL,        'WETLAND'),
('drowned_eel',           'AQUATIC',     50,'AGGRESSIVE','NOCTURNAL',  1,'ELECTRIC',  'WETLAND'),
('mire_leech_cluster',    'AQUATIC',     20,'AGGRESSIVE','NOCTURNAL',  1,'DISEASE',   'WETLAND'),
('glassfin_pike',         'AQUATIC',     40,'DEFENSIVE', 'DIURNAL',    1,NULL,        'WETLAND'),
('willow_wisp_swarm',     'AERIAL',      15,'PASSIVE',   'NOCTURNAL',  2,'DISORIENT', 'WETLAND'),
('ashhorn_antelope',      'TERRESTRIAL', 35,'PASSIVE',   'DIURNAL',    2,NULL,        'GRASSLAND'),
('burrow_ogre',           'TERRESTRIAL', 75,'DEFENSIVE', 'NOCTURNAL',  1,'GROUND_COLLAPSE','GRASSLAND'),
('dust_mantis',           'TERRESTRIAL', 45,'AGGRESSIVE','DIURNAL',    1,'CAMOUFLAGE','GRASSLAND'),
('cinder_jackal_pack',    'TERRESTRIAL', 50,'AGGRESSIVE','CREPUSCULAR',2,NULL,        'GRASSLAND'),
('thunder_lizard',        'TERRESTRIAL', 95,'DEFENSIVE', 'DIURNAL',    2,'TREMOR_WARNING','GRASSLAND'),
('glass_scavenger_beetle','TERRESTRIAL', 25,'PASSIVE',   'DIURNAL',    1,NULL,        'GRASSLAND'),
('crag_hyena',            'TERRESTRIAL', 55,'AGGRESSIVE','NOCTURNAL',  2,NULL,        'MOUNTAIN,HIGHLAND'),
('stonehorn_ram',         'TERRESTRIAL', 60,'DEFENSIVE', 'DIURNAL',    1,NULL,        'MOUNTAIN,HIGHLAND'),
('cave_screecher',        'AERIAL',      40,'AGGRESSIVE','NOCTURNAL',  1,'ECHOLOCATION','MOUNTAIN'),
('ironmaw_mole',          'TERRESTRIAL', 50,'DEFENSIVE', 'NOCTURNAL',  1,'GROUND_COLLAPSE','MOUNTAIN,HIGHLAND'),
('frostwing_owl',         'AERIAL',      35,'PASSIVE',   'NOCTURNAL',  2,NULL,        'HIGHLAND,MOUNTAIN'),
('ember_newt',            'AMPHIBIOUS',  20,'DEFENSIVE', 'NOCTURNAL',  1,'HEAT_HAZARD','WETLAND'),
('saltback_crocodilian',  'AMPHIBIOUS', 100,'APEX',      'NOCTURNAL',  1,NULL,        'COAST,WETLAND'),
('wave_roc',              'AERIAL',      90,'APEX',      'DIURNAL',    3,NULL,        'COAST,MOUNTAIN'),
('storm_moth_cloud',      'AERIAL',      15,'PASSIVE',   'NOCTURNAL',  2,'SWARM',     'GRASSLAND,COAST'),
('bonecrab',              'AMPHIBIOUS',  35,'DEFENSIVE', 'NOCTURNAL',  1,NULL,        'COAST'),
('pale_wolf',             'TERRESTRIAL', 60,'AGGRESSIVE','NOCTURNAL',  2,NULL,        'HIGHLAND,MOUNTAIN'),
('worldroot_serpent',     'TERRESTRIAL',110,'APEX',      'NOCTURNAL',  2,NULL,        'TEMPERATE_FOREST,MOUNTAIN')
ON CONFLICT (species_key) DO NOTHING;
